/*
 * This source file was generated by the Gradle 'init' task
 */
package platformer;

import processing.core.PApplet;

public class App extends PApplet {
    

    @Override
    public void settings() {
        size(800, 600); // Set the size of the window
    }

    @Override
    public void setup() {
        // Initialize variables or game state
    }

    @Override
    public void draw() {
        background(0); // Black background
    }

    public static void main(String[] args) {
        PApplet.main("platformer.App");
    }
}
