/*
 * This source file was generated by the Gradle 'init' task
 */
package platformer;

import processing.core.PApplet;

public class App extends PApplet {

    private final int WIDTH = 800;
    private final int HEIGHT = 600;
    private final int FPS = 60;
    

    @Override
    public void settings() {
        size(WIDTH, HEIGHT); // Set the size of the window
    }

    // Initialize variables or game state
    @Override
    public void setup() {
        frameRate(FPS);
    }

    @Override
    public void draw() {
        background(16, 194, 109); // Black background
    }

    // Close window when key is pressed
    @Override
    public void keyPressed() {
        if (key == 'q' || key == 'Q') {  // Press 'Q' to quit
            exit();  // Close the window
        }
    }

    public static void main(String[] args) {
        PApplet.main("platformer.App");
    }
}
